"""Owned GDI window fixture. Never moves, paints or closes a foreign HWND."""
import ctypes
from ctypes import wintypes as w
import os
import time
import uuid
from concurrent.futures import Future
import queue
import threading

from quest3d.window_sources import Win32WindowProvider


class OwnedWindowFixture:
    def __init__(self):
        self.provider = Win32WindowProvider()
        self.user, self.kernel = self.provider.user, self.provider.kernel
        self.gdi = ctypes.WinDLL("gdi32", use_last_error=True)
        self.windows = {}
        self.class_name = "Quest3DWindowFixture" + uuid.uuid4().hex
        self.callback_type = ctypes.WINFUNCTYPE(ctypes.c_ssize_t, w.HWND, w.UINT, w.WPARAM, w.LPARAM)
        callback_type = self.callback_type
        class WindowClass(ctypes.Structure):
            _fields_ = [("style", w.UINT), ("proc", callback_type), ("class_extra", ctypes.c_int),
                ("window_extra", ctypes.c_int), ("instance", w.HINSTANCE), ("icon", w.HICON),
                ("cursor", w.HANDLE), ("background", w.HBRUSH), ("menu", w.LPCWSTR), ("name", w.LPCWSTR)]
        class Paint(ctypes.Structure):
            _fields_ = [("dc", w.HDC), ("erase", w.BOOL), ("rect", w.RECT),
                ("restore", w.BOOL), ("inc_update", w.BOOL), ("reserved", ctypes.c_ubyte * 32)]
        self.Paint, self.WindowClass = Paint, WindowClass
        self.user.DefWindowProcW.argtypes = [w.HWND, w.UINT, w.WPARAM, w.LPARAM]
        self.user.DefWindowProcW.restype = ctypes.c_ssize_t
        self.user.RegisterClassW.argtypes, self.user.RegisterClassW.restype = [ctypes.POINTER(WindowClass)], w.WORD
        self.user.UnregisterClassW.argtypes, self.user.UnregisterClassW.restype = [w.LPCWSTR, w.HINSTANCE], w.BOOL
        self.user.BeginPaint.argtypes, self.user.BeginPaint.restype = [w.HWND, ctypes.POINTER(Paint)], w.HDC
        self.user.EndPaint.argtypes, self.user.EndPaint.restype = [w.HWND, ctypes.POINTER(Paint)], w.BOOL
        self.user.FillRect.argtypes, self.user.FillRect.restype = [w.HDC, ctypes.POINTER(w.RECT), w.HBRUSH], ctypes.c_int
        self.user.CreateWindowExW.argtypes = [w.DWORD, w.LPCWSTR, w.LPCWSTR, w.DWORD, ctypes.c_int,
            ctypes.c_int, ctypes.c_int, ctypes.c_int, w.HWND, w.HMENU, w.HINSTANCE, ctypes.c_void_p]
        self.user.CreateWindowExW.restype = w.HWND
        self.user.ShowWindow.argtypes, self.user.ShowWindow.restype = [w.HWND, ctypes.c_int], w.BOOL
        self.user.SetWindowPos.argtypes = [w.HWND, w.HWND, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int, w.UINT]
        self.user.SetWindowPos.restype = w.BOOL
        self.user.DestroyWindow.argtypes, self.user.DestroyWindow.restype = [w.HWND], w.BOOL
        self.user.InvalidateRect.argtypes, self.user.InvalidateRect.restype = [w.HWND, ctypes.POINTER(w.RECT), w.BOOL], w.BOOL
        self.user.UpdateWindow.argtypes, self.user.UpdateWindow.restype = [w.HWND], w.BOOL
        self.user.PeekMessageW.argtypes, self.user.PeekMessageW.restype = [ctypes.POINTER(w.MSG), w.HWND, w.UINT, w.UINT, w.UINT], w.BOOL
        self.user.TranslateMessage.argtypes = [ctypes.POINTER(w.MSG)]
        self.user.DispatchMessageW.argtypes, self.user.DispatchMessageW.restype = [ctypes.POINTER(w.MSG)], ctypes.c_ssize_t
        self.kernel.GetModuleHandleW.argtypes, self.kernel.GetModuleHandleW.restype = [w.LPCWSTR], w.HMODULE
        self.gdi.CreateSolidBrush.argtypes, self.gdi.CreateSolidBrush.restype = [w.DWORD], w.HBRUSH
        self.gdi.DeleteObject.argtypes, self.gdi.DeleteObject.restype = [w.HANDLE], w.BOOL
        self.instance = self.kernel.GetModuleHandleW(None)
        self.callback = callback_type(self._proc)
        self.window_class = WindowClass(0, self.callback, 0, 0, self.instance, None, None, None, None, self.class_name)
        self.atom = 0
        self.foreground_before = int(self.user.GetForegroundWindow() or 0)

    def _fill(self, dc, rectangle, color):
        brush = self.gdi.CreateSolidBrush(color)
        try:
            self.user.FillRect(dc, ctypes.byref(rectangle), brush)
        finally:
            self.gdi.DeleteObject(brush)

    def _proc(self, hwnd, message, wp, lp):
        if message == 0xF:  # WM_PAINT; data is generated by this test only.
            paint = self.Paint()
            dc = self.user.BeginPaint(hwnd, ctypes.byref(paint))
            try:
                rect = w.RECT()
                self.user.GetClientRect(hwnd, ctypes.byref(rect))
                state = self.windows.get(int(hwnd), {"color": 0xFFFFFF, "phase": 0})
                state["wm_paint_count"] = state.get("wm_paint_count", 0) + 1
                self._fill(dc, rect, state["color"])
                # Small changing stripe proves fresh source frames under an occluder.
                stripe = w.RECT(8, 8, 48, 28)
                self._fill(dc, stripe, 0x0000FF if state["phase"] % 2 else 0xFF0000)
            finally:
                self.user.EndPaint(hwnd, ctypes.byref(paint))
            return 0
        return self.user.DefWindowProcW(hwnd, message, wp, lp)

    def __enter__(self):
        self.atom = self.user.RegisterClassW(ctypes.byref(self.window_class))
        if not self.atom:
            raise ctypes.WinError(ctypes.get_last_error())
        return self

    def owned(self, hwnd):
        if hwnd not in self.windows or self.provider._pid(hwnd)[0] != os.getpid():
            raise RuntimeError("Refusing to change foreign HWND")
        return hwnd

    def create(self, *, left=2700, top=200, width=420, height=300, color=0xFFFFFF, single_paint=False):
        with self.provider.physical_pixels():
            hwnd = self.user.CreateWindowExW(0x08000080, self.class_name, "Quest3D owned WGC source", 0x00CF0000,
                left, top, width, height, None, None, self.instance, None)
        if not hwnd:
            raise ctypes.WinError(ctypes.get_last_error())
        hwnd = int(hwnd)
        self.windows[hwnd] = {"color": color, "phase": 0, "wm_paint_count": 0}
        if single_paint:
            self.user.ShowWindow(self.owned(hwnd), 8)
            self.user.UpdateWindow(hwnd)
            self.pump()
            return hwnd
        self.show(hwnd, 8)
        self.move(hwnd, left, top, width, height)
        self.paint(hwnd)
        return hwnd

    def show(self, hwnd, command):
        self.user.ShowWindow(self.owned(hwnd), command)
        self.pump()

    def move(self, hwnd, left, top, width, height):
        with self.provider.physical_pixels():
            if not self.user.SetWindowPos(self.owned(hwnd), ctypes.c_void_p(-1), left, top, width, height, 0x10):
                raise ctypes.WinError(ctypes.get_last_error())
        self.paint(hwnd)

    def paint(self, hwnd):
        self.windows[self.owned(hwnd)]["phase"] += 1
        self.user.InvalidateRect(hwnd, None, False)
        self.user.UpdateWindow(hwnd)
        self.pump()

    def paint_observation(self, hwnd):
        return dict(self.windows[self.owned(hwnd)])

    def pump(self, seconds=0):
        deadline = time.monotonic() + seconds
        message = w.MSG()
        while True:
            while self.user.PeekMessageW(ctypes.byref(message), None, 0, 0, 1):
                self.user.TranslateMessage(ctypes.byref(message))
                self.user.DispatchMessageW(ctypes.byref(message))
            if time.monotonic() >= deadline:
                return
            time.sleep(.005)

    def close_window(self, hwnd):
        if not self.user.DestroyWindow(self.owned(hwnd)):
            raise ctypes.WinError(ctypes.get_last_error())
        del self.windows[hwnd]
        self.pump()

    def __exit__(self, *_):
        for hwnd in list(self.windows):
            self.close_window(hwnd)
        if self.atom:
            self.user.UnregisterClassW(self.class_name, self.instance)
        self.pump()


class ThreadedOwnedWindowFixture:
    """Dedicated UI message loop, so capture/grab/close never blocks source UI."""
    def __init__(self):
        self.commands = queue.Queue()
        self.ready = Future()
        self.provider = Win32WindowProvider(include_titles=False)
        self.user = self.provider.user
        self.thread = threading.Thread(target=self._run, name="Owned HWND fixture UI", daemon=True)

    def _run(self):
        try:
            with OwnedWindowFixture() as fixture:
                self.ready.set_result(fixture.foreground_before)
                while True:
                    fixture.pump()
                    try:
                        method, args, kwargs, done = self.commands.get(timeout=.005)
                    except queue.Empty:
                        continue
                    if method is None:
                        done.set_result(None)
                        break
                    try:
                        done.set_result(getattr(fixture, method)(*args, **kwargs))
                    except BaseException as exc:
                        done.set_exception(exc)
        except BaseException as exc:
            if not self.ready.done():
                self.ready.set_exception(exc)
            else:
                raise

    def __enter__(self):
        self.thread.start()
        self.foreground_before = self.ready.result(timeout=5)
        return self

    def _call(self, method, *args, **kwargs):
        done = Future()
        self.commands.put((method, args, kwargs, done))
        return done.result(timeout=5)

    def __getattr__(self, name):
        if name in ("create", "move", "paint", "paint_observation", "show", "pump", "close_window"):
            return lambda *args, **kwargs: self._call(name, *args, **kwargs)
        raise AttributeError(name)

    def __exit__(self, *_):
        self._call(None)
        self.thread.join(5)
        if self.thread.is_alive():
            raise RuntimeError("Owned fixture UI failed to stop")

